// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhasePlayWeb.Data;

#nullable disable

namespace PhasePlayWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250726131754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.AttributeSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SetID")
                        .HasColumnType("integer");

                    b.Property<int>("attributeID")
                        .HasColumnType("integer");

                    b.Property<string>("order")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SetID");

                    b.HasIndex("attributeID");

                    b.ToTable("AttributeSets");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Excercises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryGroup")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryGroup1")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryGroup2")
                        .HasColumnType("text");

                    b.Property<string>("YoutubeURL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Excercises");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.ExerciseSetAttrib", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("ExcerciseID")
                        .HasColumnType("integer");

                    b.Property<string>("ExcerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PAExerciseID")
                        .HasColumnType("integer");

                    b.Property<int?>("PerWeek")
                        .HasColumnType("integer");

                    b.Property<double?>("RM")
                        .HasColumnType("double precision");

                    b.Property<double?>("RPE")
                        .HasColumnType("double precision");

                    b.Property<int>("SchemaID")
                        .HasColumnType("integer");

                    b.Property<int?>("SupersetID")
                        .HasColumnType("integer");

                    b.Property<string>("Velocity")
                        .HasColumnType("text");

                    b.Property<int>("reps")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ExcerciseID");

                    b.HasIndex("PAExerciseID");

                    b.HasIndex("SchemaID");

                    b.ToTable("SetExcercises");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.GroupMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.GroupProgramme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<int>("programmeId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("GroupProgrammes");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.GroupSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupProgrammeID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("EventID");

                    b.HasIndex("GroupProgrammeID");

                    b.ToTable("GroupSession");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.MissedSessions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("GroupProgrammeId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupSessionID")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("MissedSessions");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.OvSetExcercises", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ExcerciseID")
                        .HasColumnType("integer");

                    b.Property<int>("OverAllSetID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ExcerciseID");

                    b.HasIndex("OverAllSetID");

                    b.ToTable("OvSetExcercises");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.OverAllSet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ProgramID");

                    b.ToTable("OverAllSets");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.PAExercise", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AddNote")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PAExercises");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.PercentRM_Mapping", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("PercentRM")
                        .HasColumnType("double precision");

                    b.Property<string>("RIR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RPE")
                        .HasColumnType("double precision");

                    b.Property<string>("VelocityRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PercentRM_Mapping");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.ProgramAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgramID");

                    b.ToTable("ProgramAttributes");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Programme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OccursOn")
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<int>("Weeks")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.S_RSchema", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("RM_Increase")
                        .HasColumnType("integer");

                    b.Property<double>("RPE_Increase")
                        .HasColumnType("double precision");

                    b.Property<int>("SetWeek")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("SRSchema");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SchemaAttributes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("PercentRM")
                        .HasColumnType("double precision");

                    b.Property<double>("RPE")
                        .HasColumnType("double precision");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaID")
                        .HasColumnType("integer");

                    b.Property<string>("Vel")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("SchemaID");

                    b.ToTable("SchemaAttributes");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Session", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExcerciseID")
                        .HasColumnType("integer");

                    b.Property<string>("ExcerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupProgrammeId")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupSessionID")
                        .HasColumnType("integer");

                    b.Property<int>("PAExerciseID")
                        .HasColumnType("integer");

                    b.Property<int?>("PerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<double?>("RM")
                        .HasColumnType("double precision");

                    b.Property<double?>("RPE")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<double?>("RecommendedWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("SchemaID")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionSetID")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Velocity")
                        .HasColumnType("text");

                    b.Property<float?>("WeightUsed")
                        .HasColumnType("real");

                    b.Property<double?>("e1RM")
                        .HasColumnType("double precision");

                    b.Property<int>("reps")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SessionDate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupProgrammeId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("EventID");

                    b.HasIndex("SessionID");

                    b.ToTable("SessionDates");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SessionHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExcerciseID")
                        .HasColumnType("integer");

                    b.Property<string>("ExcerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupProgrammeId")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupSessionID")
                        .HasColumnType("integer");

                    b.Property<int>("PAExerciseID")
                        .HasColumnType("integer");

                    b.Property<int?>("PerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<double?>("RM")
                        .HasColumnType("double precision");

                    b.Property<double?>("RPE")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<double?>("RecommendedWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("SchemaID")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionSetID")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Velocity")
                        .HasColumnType("text");

                    b.Property<float?>("WeightUsed")
                        .HasColumnType("real");

                    b.Property<int>("reps")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionHistory");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SessionSet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseSetAttribID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupSessionID")
                        .HasColumnType("integer");

                    b.Property<int>("PAExerciseID")
                        .HasColumnType("integer");

                    b.Property<int?>("PerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ProgrammeID")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ExerciseSetAttribID");

                    b.HasIndex("GroupSessionID");

                    b.HasIndex("PAExerciseID");

                    b.HasIndex("ProgrammeID");

                    b.ToTable("SessionSet");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SetAttributes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ExcercisesId")
                        .HasColumnType("integer");

                    b.Property<int>("SetID")
                        .HasColumnType("integer");

                    b.Property<int?>("SetNumber")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ExcercisesId");

                    b.HasIndex("SetID");

                    b.ToTable("SetAttributes");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Superset", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("PAExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("restperiod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Supersets");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SupersetExcerciseAttr", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("SupersetID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("SupersetExcerciseAttr");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.TeamMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<float?>("BodyWeight")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("FirstSignIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.UserExercises", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("category")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("UserExercises");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.UserSRSchema", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("SetWeek")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("userSRSchemas");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.UserSchemaAttributes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("PercentRM")
                        .HasColumnType("integer");

                    b.Property<double>("RPE")
                        .HasColumnType("double precision");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("UserSRSchemaId")
                        .HasColumnType("integer");

                    b.Property<int?>("Vel")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("userSchemaAttributes");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupProgrammeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Workout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ExcerciseID")
                        .HasColumnType("integer");

                    b.Property<string>("ExcerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PerWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("RM")
                        .HasColumnType("integer");

                    b.Property<double?>("RPE")
                        .HasColumnType("double precision");

                    b.Property<int>("SchemaID")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Velocity")
                        .HasColumnType("text");

                    b.Property<int>("reps")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SchemaID");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.AttributeSet", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.PAExercise", "Sets")
                        .WithMany()
                        .HasForeignKey("SetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.ProgramAttributes", "ProgramAttributes")
                        .WithMany()
                        .HasForeignKey("attributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramAttributes");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.ExerciseSetAttrib", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Excercises", "Excercises")
                        .WithMany()
                        .HasForeignKey("ExcerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.PAExercise", "PAExercise")
                        .WithMany()
                        .HasForeignKey("PAExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.S_RSchema", "S_RSchema")
                        .WithMany()
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercises");

                    b.Navigation("PAExercise");

                    b.Navigation("S_RSchema");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.GroupSession", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.GroupProgramme", "GroupProgramme")
                        .WithMany()
                        .HasForeignKey("GroupProgrammeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("GroupProgramme");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Groups", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Teams", "Teams")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.MissedSessions", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.OvSetExcercises", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Excercises", "Excercise")
                        .WithMany()
                        .HasForeignKey("ExcerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.OverAllSet", "OverAllSet")
                        .WithMany()
                        .HasForeignKey("OverAllSetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercise");

                    b.Navigation("OverAllSet");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.OverAllSet", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.ProgramAttributes", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SchemaAttributes", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.S_RSchema", "S_RSchema")
                        .WithMany()
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("S_RSchema");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Session", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SessionDate", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SessionHistory", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SessionSet", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.ExerciseSetAttrib", "ExerciseSetAttrib")
                        .WithMany()
                        .HasForeignKey("ExerciseSetAttribID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.GroupSession", "GroupSession")
                        .WithMany()
                        .HasForeignKey("GroupSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.PAExercise", "PaExercise")
                        .WithMany()
                        .HasForeignKey("PAExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseSetAttrib");

                    b.Navigation("GroupSession");

                    b.Navigation("PaExercise");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.SetAttributes", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.Excercises", "Excercises")
                        .WithMany()
                        .HasForeignKey("ExcercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhasePlayWeb.Models.Entities.PAExercise", "Sets")
                        .WithMany()
                        .HasForeignKey("SetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercises");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Teams", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.User", "User")
                        .WithMany("teams")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.Workout", b =>
                {
                    b.HasOne("PhasePlayWeb.Models.Entities.S_RSchema", "S_RSchema")
                        .WithMany()
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("S_RSchema");
                });

            modelBuilder.Entity("PhasePlayWeb.Models.Entities.User", b =>
                {
                    b.Navigation("teams");
                });
#pragma warning restore 612, 618
        }
    }
}
